name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake sdl2 sdl2_ttf

    - name: Install dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
        choco install sdl2 sdl2-ttf -y

    - name: Configure CMake
      if: runner.os == 'macOS'
      run: |
        brew_prefix=$(brew --prefix)
        cmake -S . -B build \
          -DCMAKE_PREFIX_PATH="$brew_prefix/opt/sdl2;$brew_prefix/opt/sdl2_ttf" \
          -DCMAKE_BUILD_TYPE=Release

    - name: Configure CMake
      if: runner.os != 'macOS'
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Check CMake cache (macOS)
      if: runner.os == 'macOS'
      run: cat build/CMakeCache.txt | grep TTF

    - name: Build
      run: cmake --build build --config Release

    - name: List build output
      run: |
        ls -l build || dir build 